/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.data.migration.tool.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EntityManager service. Represents a row in the &quot;SYNC_EntityManager&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.data.migration.tool.model.impl.EntityManagerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.data.migration.tool.model.impl.EntityManagerImpl}.
 * </p>
 *
 * @author Dylan Rebelak
 * @see EntityManager
 * @see com.liferay.data.migration.tool.model.impl.EntityManagerImpl
 * @see com.liferay.data.migration.tool.model.impl.EntityManagerModelImpl
 * @generated
 */
@ProviderType
public interface EntityManagerModel extends BaseModel<EntityManager> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a entity manager model instance should use the {@link EntityManager} interface instead.
	 */

	/**
	 * Returns the primary key of this entity manager.
	 *
	 * @return the primary key of this entity manager
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this entity manager.
	 *
	 * @param primaryKey the primary key of this entity manager
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the entity name of this entity manager.
	 *
	 * @return the entity name of this entity manager
	 */
	@AutoEscape
	public String getEntityName();

	/**
	 * Sets the entity name of this entity manager.
	 *
	 * @param entityName the entity name of this entity manager
	 */
	public void setEntityName(String entityName);

	/**
	 * Returns the last sync date of this entity manager.
	 *
	 * @return the last sync date of this entity manager
	 */
	public Date getLastSyncDate();

	/**
	 * Sets the last sync date of this entity manager.
	 *
	 * @param lastSyncDate the last sync date of this entity manager
	 */
	public void setLastSyncDate(Date lastSyncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EntityManager entityManager);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EntityManager> toCacheModel();

	@Override
	public EntityManager toEscapedModel();

	@Override
	public EntityManager toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}