/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.data.migration.tool.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MigrationManager service. Represents a row in the &quot;SYNC_MigrationManager&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.data.migration.tool.model.impl.MigrationManagerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.data.migration.tool.model.impl.MigrationManagerImpl}.
 * </p>
 *
 * @author Dylan Rebelak
 * @see MigrationManager
 * @see com.liferay.data.migration.tool.model.impl.MigrationManagerImpl
 * @see com.liferay.data.migration.tool.model.impl.MigrationManagerModelImpl
 * @generated
 */
@ProviderType
public interface MigrationManagerModel extends BaseModel<MigrationManager> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a migration manager model instance should use the {@link MigrationManager} interface instead.
	 */

	/**
	 * Returns the primary key of this migration manager.
	 *
	 * @return the primary key of this migration manager
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this migration manager.
	 *
	 * @param primaryKey the primary key of this migration manager
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the manager ID of this migration manager.
	 *
	 * @return the manager ID of this migration manager
	 */
	public long getManagerId();

	/**
	 * Sets the manager ID of this migration manager.
	 *
	 * @param managerId the manager ID of this migration manager
	 */
	public void setManagerId(long managerId);

	/**
	 * Returns the time started of this migration manager.
	 *
	 * @return the time started of this migration manager
	 */
	public Date getTimeStarted();

	/**
	 * Sets the time started of this migration manager.
	 *
	 * @param timeStarted the time started of this migration manager
	 */
	public void setTimeStarted(Date timeStarted);

	/**
	 * Returns the time completed of this migration manager.
	 *
	 * @return the time completed of this migration manager
	 */
	public Date getTimeCompleted();

	/**
	 * Sets the time completed of this migration manager.
	 *
	 * @param timeCompleted the time completed of this migration manager
	 */
	public void setTimeCompleted(Date timeCompleted);

	/**
	 * Returns the from date of this migration manager.
	 *
	 * @return the from date of this migration manager
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this migration manager.
	 *
	 * @param fromDate the from date of this migration manager
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the records synced of this migration manager.
	 *
	 * @return the records synced of this migration manager
	 */
	public long getRecordsSynced();

	/**
	 * Sets the records synced of this migration manager.
	 *
	 * @param recordsSynced the records synced of this migration manager
	 */
	public void setRecordsSynced(long recordsSynced);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MigrationManager migrationManager);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MigrationManager> toCacheModel();

	@Override
	public MigrationManager toEscapedModel();

	@Override
	public MigrationManager toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}